import mutations from "./mutations.js";
import actions from "./actions.js";
import getters from "./getters.js";

export default {
  namespaced: true,
  state() {
    return {
      products: [
        {
          _id: "61b1d9266e8446d03a2df54c",
          company: "EXOBLUE",
          tags: "jordan",
          color: "#344CB7",
          image:
            "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
          imgText: "Lorem",
          slider: [
            {
              _id: "61b2063629949e4363853a22",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "CENTREXIN",
              description:
                "Ad consequat eu exercitation dolor nostrud nostrud anim amet ex proident duis amet sit eu. Qui velit sunt id incididunt sunt. Voluptate aliquip veniam culpa ex aliquip irure ipsum nostrud anim reprehenderit non. Ex elit reprehenderit dolore voluptate fugiat labore ipsum consequat eu proident. Consequat duis aliquip dolor dolore. Lorem deserunt nulla dolore sit sint deserunt laboris.\r\n",
              tags: "vapormax",
              color: "#344CB7",
              price: 147.16,
              amount: 1687,
              size: "420x297mm",
              count: 1129,
            },
            {
              _id: "61b206365861aa495b3ca71f",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "ULTRIMAX",
              description:
                "Incididunt nulla velit officia deserunt commodo culpa est esse. Duis nulla sit enim eiusmod. Et id qui occaecat non eu aliquip occaecat laboris nulla occaecat in. Ullamco in esse do amet cupidatat laboris eiusmod proident consectetur id. Elit irure laborum enim ipsum ad ipsum est. Cupidatat proident adipisicing reprehenderit id consectetur duis eu amet sint elit amet occaecat amet.\r\n",
              tags: "vapormax",
              color: "#FF00E4",
              price: 129.97,
              amount: 2546,
              size: "420x297mm",
              count: 1337,
            },
            {
              _id: "61b2063636b6a368b3360c55",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "FUTURITY",
              description:
                "Dolor ad consequat elit culpa non sunt elit tempor est fugiat. Occaecat qui nostrud velit adipisicing occaecat sint consequat qui exercitation irure amet nostrud magna. Cupidatat elit occaecat ipsum exercitation mollit quis sit Lorem sint velit cupidatat consequat adipisicing enim. Quis deserunt velit quis enim reprehenderit laboris proident duis non culpa pariatur. Fugiat quis magna consequat labore aliqua ea laborum laboris non id fugiat reprehenderit. Minim incididunt tempor eu magna nisi culpa est.\r\n",
              tags: "vapormax",
              color: "#62A8AC",
              price: 110.39,
              amount: 2924,
              size: "420x297mm",
              count: 1187,
            },
            {
              _id: "61b2063689061e939f61f90a",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "ONTAGENE",
              description:
                "Est incididunt deserunt occaecat cupidatat fugiat qui incididunt fugiat. Velit Lorem ut pariatur est ea esse. Ullamco esse elit consectetur ad velit labore sint fugiat aliquip. Aute non sint nisi laboris officia occaecat nisi. Minim incididunt commodo dolore esse laboris magna proident mollit ex do nostrud excepteur irure velit. Fugiat eiusmod laborum aliquip eiusmod ad reprehenderit non elit anim amet labore nostrud sint.\r\n",
              tags: "vapormax",
              color: "#62A8AC",
              price: 196.7,
              amount: 2481,
              size: "420x297mm",
              count: 1093,
            },
            {
              _id: "61b20636209255a39c2f7623",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "DIGIGEN",
              description:
                "Commodo cupidatat ad culpa exercitation tempor. Culpa eiusmod nisi laborum minim dolor. In voluptate adipisicing veniam occaecat aliqua excepteur incididunt Lorem ea. Elit aute non sit in nulla tempor Lorem culpa ad. Velit incididunt incididunt magna veniam do adipisicing dolore commodo deserunt sint. Et tempor dolore officia sint.\r\n",
              tags: "vapormax",
              color: "#344CB7",
              price: 205.22,
              amount: 2371,
              size: "420x297mm",
              count: 2202,
            },
          ],
        },
        {
          _id: "61b1d926c7c1018c3055b536",
          company: "MACRONAUT",
          tags: "jordan",
          color: "#62A8AC",
          image:
            "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
          imgText: "Lorem",
          slider: [
            {
              _id: "61b2063629949e4363853a22",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "CENTREXIN",
              description:
                "Ad consequat eu exercitation dolor nostrud nostrud anim amet ex proident duis amet sit eu. Qui velit sunt id incididunt sunt. Voluptate aliquip veniam culpa ex aliquip irure ipsum nostrud anim reprehenderit non. Ex elit reprehenderit dolore voluptate fugiat labore ipsum consequat eu proident. Consequat duis aliquip dolor dolore. Lorem deserunt nulla dolore sit sint deserunt laboris.\r\n",
              tags: "vapormax",
              color: "#344CB7",
              price: 147.16,
              amount: 1687,
              size: "420x297mm",
              count: 1129,
            },
            {
              _id: "61b206365861aa495b3ca71f",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "ULTRIMAX",
              description:
                "Incididunt nulla velit officia deserunt commodo culpa est esse. Duis nulla sit enim eiusmod. Et id qui occaecat non eu aliquip occaecat laboris nulla occaecat in. Ullamco in esse do amet cupidatat laboris eiusmod proident consectetur id. Elit irure laborum enim ipsum ad ipsum est. Cupidatat proident adipisicing reprehenderit id consectetur duis eu amet sint elit amet occaecat amet.\r\n",
              tags: "vapormax",
              color: "#FF00E4",
              price: 129.97,
              amount: 2546,
              size: "420x297mm",
              count: 1337,
            },
            {
              _id: "61b2063636b6a368b3360c55",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "FUTURITY",
              description:
                "Dolor ad consequat elit culpa non sunt elit tempor est fugiat. Occaecat qui nostrud velit adipisicing occaecat sint consequat qui exercitation irure amet nostrud magna. Cupidatat elit occaecat ipsum exercitation mollit quis sit Lorem sint velit cupidatat consequat adipisicing enim. Quis deserunt velit quis enim reprehenderit laboris proident duis non culpa pariatur. Fugiat quis magna consequat labore aliqua ea laborum laboris non id fugiat reprehenderit. Minim incididunt tempor eu magna nisi culpa est.\r\n",
              tags: "vapormax",
              color: "#62A8AC",
              price: 110.39,
              amount: 2924,
              size: "420x297mm",
              count: 1187,
            },
            {
              _id: "61b2063689061e939f61f90a",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "ONTAGENE",
              description:
                "Est incididunt deserunt occaecat cupidatat fugiat qui incididunt fugiat. Velit Lorem ut pariatur est ea esse. Ullamco esse elit consectetur ad velit labore sint fugiat aliquip. Aute non sint nisi laboris officia occaecat nisi. Minim incididunt commodo dolore esse laboris magna proident mollit ex do nostrud excepteur irure velit. Fugiat eiusmod laborum aliquip eiusmod ad reprehenderit non elit anim amet labore nostrud sint.\r\n",
              tags: "vapormax",
              color: "#62A8AC",
              price: 196.7,
              amount: 2481,
              size: "420x297mm",
              count: 1093,
            },
            {
              _id: "61b20636209255a39c2f7623",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "DIGIGEN",
              description:
                "Commodo cupidatat ad culpa exercitation tempor. Culpa eiusmod nisi laborum minim dolor. In voluptate adipisicing veniam occaecat aliqua excepteur incididunt Lorem ea. Elit aute non sit in nulla tempor Lorem culpa ad. Velit incididunt incididunt magna veniam do adipisicing dolore commodo deserunt sint. Et tempor dolore officia sint.\r\n",
              tags: "vapormax",
              color: "#344CB7",
              price: 205.22,
              amount: 2371,
              size: "420x297mm",
              count: 2202,
            },
          ],
        },
        {
          _id: "61b1d9260d3f996109eb654a",
          company: "MANTRIX",
          tags: "jordan",
          color: "#344CB7",
          image:
            "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
          imgText: "Lorem",
          slider: [
            {
              _id: "61b2063629949e4363853a22",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "CENTREXIN",
              description:
                "Ad consequat eu exercitation dolor nostrud nostrud anim amet ex proident duis amet sit eu. Qui velit sunt id incididunt sunt. Voluptate aliquip veniam culpa ex aliquip irure ipsum nostrud anim reprehenderit non. Ex elit reprehenderit dolore voluptate fugiat labore ipsum consequat eu proident. Consequat duis aliquip dolor dolore. Lorem deserunt nulla dolore sit sint deserunt laboris.\r\n",
              tags: "vapormax",
              color: "#344CB7",
              price: 147.16,
              amount: 1687,
              size: "420x297mm",
              count: 1129,
            },
            {
              _id: "61b206365861aa495b3ca71f",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "ULTRIMAX",
              description:
                "Incididunt nulla velit officia deserunt commodo culpa est esse. Duis nulla sit enim eiusmod. Et id qui occaecat non eu aliquip occaecat laboris nulla occaecat in. Ullamco in esse do amet cupidatat laboris eiusmod proident consectetur id. Elit irure laborum enim ipsum ad ipsum est. Cupidatat proident adipisicing reprehenderit id consectetur duis eu amet sint elit amet occaecat amet.\r\n",
              tags: "vapormax",
              color: "#FF00E4",
              price: 129.97,
              amount: 2546,
              size: "420x297mm",
              count: 1337,
            },
            {
              _id: "61b2063636b6a368b3360c55",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "FUTURITY",
              description:
                "Dolor ad consequat elit culpa non sunt elit tempor est fugiat. Occaecat qui nostrud velit adipisicing occaecat sint consequat qui exercitation irure amet nostrud magna. Cupidatat elit occaecat ipsum exercitation mollit quis sit Lorem sint velit cupidatat consequat adipisicing enim. Quis deserunt velit quis enim reprehenderit laboris proident duis non culpa pariatur. Fugiat quis magna consequat labore aliqua ea laborum laboris non id fugiat reprehenderit. Minim incididunt tempor eu magna nisi culpa est.\r\n",
              tags: "vapormax",
              color: "#62A8AC",
              price: 110.39,
              amount: 2924,
              size: "420x297mm",
              count: 1187,
            },
            {
              _id: "61b2063689061e939f61f90a",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "ONTAGENE",
              description:
                "Est incididunt deserunt occaecat cupidatat fugiat qui incididunt fugiat. Velit Lorem ut pariatur est ea esse. Ullamco esse elit consectetur ad velit labore sint fugiat aliquip. Aute non sint nisi laboris officia occaecat nisi. Minim incididunt commodo dolore esse laboris magna proident mollit ex do nostrud excepteur irure velit. Fugiat eiusmod laborum aliquip eiusmod ad reprehenderit non elit anim amet labore nostrud sint.\r\n",
              tags: "vapormax",
              color: "#62A8AC",
              price: 196.7,
              amount: 2481,
              size: "420x297mm",
              count: 1093,
            },
            {
              _id: "61b20636209255a39c2f7623",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "DIGIGEN",
              description:
                "Commodo cupidatat ad culpa exercitation tempor. Culpa eiusmod nisi laborum minim dolor. In voluptate adipisicing veniam occaecat aliqua excepteur incididunt Lorem ea. Elit aute non sit in nulla tempor Lorem culpa ad. Velit incididunt incididunt magna veniam do adipisicing dolore commodo deserunt sint. Et tempor dolore officia sint.\r\n",
              tags: "vapormax",
              color: "#344CB7",
              price: 205.22,
              amount: 2371,
              size: "420x297mm",
              count: 2202,
            },
          ],
        },
        {
          _id: "61b1d92663fe5bd6dac24d19",
          company: "MEGALL",
          tags: "vapormax",
          color: "#FF00E4",
          image:
            "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
          imgText: "Lorem",
          slider: [
            {
              _id: "61b2063629949e4363853a22",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "CENTREXIN",
              description:
                "Ad consequat eu exercitation dolor nostrud nostrud anim amet ex proident duis amet sit eu. Qui velit sunt id incididunt sunt. Voluptate aliquip veniam culpa ex aliquip irure ipsum nostrud anim reprehenderit non. Ex elit reprehenderit dolore voluptate fugiat labore ipsum consequat eu proident. Consequat duis aliquip dolor dolore. Lorem deserunt nulla dolore sit sint deserunt laboris.\r\n",
              tags: "vapormax",
              color: "#344CB7",
              price: 147.16,
              amount: 1687,
              size: "420x297mm",
              count: 1129,
            },
            {
              _id: "61b206365861aa495b3ca71f",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "ULTRIMAX",
              description:
                "Incididunt nulla velit officia deserunt commodo culpa est esse. Duis nulla sit enim eiusmod. Et id qui occaecat non eu aliquip occaecat laboris nulla occaecat in. Ullamco in esse do amet cupidatat laboris eiusmod proident consectetur id. Elit irure laborum enim ipsum ad ipsum est. Cupidatat proident adipisicing reprehenderit id consectetur duis eu amet sint elit amet occaecat amet.\r\n",
              tags: "vapormax",
              color: "#FF00E4",
              price: 129.97,
              amount: 2546,
              size: "420x297mm",
              count: 1337,
            },
            {
              _id: "61b2063636b6a368b3360c55",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "FUTURITY",
              description:
                "Dolor ad consequat elit culpa non sunt elit tempor est fugiat. Occaecat qui nostrud velit adipisicing occaecat sint consequat qui exercitation irure amet nostrud magna. Cupidatat elit occaecat ipsum exercitation mollit quis sit Lorem sint velit cupidatat consequat adipisicing enim. Quis deserunt velit quis enim reprehenderit laboris proident duis non culpa pariatur. Fugiat quis magna consequat labore aliqua ea laborum laboris non id fugiat reprehenderit. Minim incididunt tempor eu magna nisi culpa est.\r\n",
              tags: "vapormax",
              color: "#62A8AC",
              price: 110.39,
              amount: 2924,
              size: "420x297mm",
              count: 1187,
            },
            {
              _id: "61b2063689061e939f61f90a",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "ONTAGENE",
              description:
                "Est incididunt deserunt occaecat cupidatat fugiat qui incididunt fugiat. Velit Lorem ut pariatur est ea esse. Ullamco esse elit consectetur ad velit labore sint fugiat aliquip. Aute non sint nisi laboris officia occaecat nisi. Minim incididunt commodo dolore esse laboris magna proident mollit ex do nostrud excepteur irure velit. Fugiat eiusmod laborum aliquip eiusmod ad reprehenderit non elit anim amet labore nostrud sint.\r\n",
              tags: "vapormax",
              color: "#62A8AC",
              price: 196.7,
              amount: 2481,
              size: "420x297mm",
              count: 1093,
            },
            {
              _id: "61b20636209255a39c2f7623",
              image: "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/y7v6sqkahxxflefbf5vx/nike-air-vapormax-pale-grey.jpg",
              name: "DIGIGEN",
              description:
                "Commodo cupidatat ad culpa exercitation tempor. Culpa eiusmod nisi laborum minim dolor. In voluptate adipisicing veniam occaecat aliqua excepteur incididunt Lorem ea. Elit aute non sit in nulla tempor Lorem culpa ad. Velit incididunt incididunt magna veniam do adipisicing dolore commodo deserunt sint. Et tempor dolore officia sint.\r\n",
              tags: "vapormax",
              color: "#344CB7",
              price: 205.22,
              amount: 2371,
              size: "420x297mm",
              count: 2202,
            },
          ],
        },
      ],
    };
  },
  mutations,
  actions,
  getters,
};
